Object.defineProperty(exports, "__esModule", { value: true });
exports.verifyCallback = exports.toUIString = exports.isUndefined = exports.isString = exports.isObject = exports.isNumber = exports.isNullOrUndefined = exports.isFunction = exports.isDefined = exports.isBoolean = exports.getClassInfo = exports.getBaseClasses = exports.getClass = exports.ClassInfo = void 0;
var core_1 = require("@nativescript/core");
exports.ClassInfo = core_1.Utils.ClassInfo;
exports.getClass = core_1.Utils.getClass;
exports.getBaseClasses = core_1.Utils.getBaseClasses;
exports.getClassInfo = core_1.Utils.getClassInfo;
exports.isBoolean = core_1.Utils.isBoolean;
exports.isDefined = core_1.Utils.isDefined;
exports.isFunction = core_1.Utils.isFunction;
exports.isNullOrUndefined = core_1.Utils.isNullOrUndefined;
exports.isNumber = core_1.Utils.isNumber;
exports.isObject = core_1.Utils.isObject;
exports.isString = core_1.Utils.isString;
exports.isUndefined = core_1.Utils.isUndefined;
exports.toUIString = core_1.Utils.toUIString;
exports.verifyCallback = core_1.Utils.verifyCallback;
