Object.defineProperty(exports, "__esModule", { value: true });
exports.disable = exports.clearWriters = exports.categories = exports.addWriter = exports.ConsoleWriter = exports.DefaultErrorHandler = exports.addEventListener = exports.addCategories = exports.removeEventListener = exports.messageType = exports.removeWriter = exports.write = exports.setErrorHandler = exports.setCategories = exports.notifyEvent = exports.isEnabled = exports.isCategorySet = exports.getErrorHandler = exports.error = exports.enable = void 0;
var core_1 = require("@nativescript/core");
exports.enable = core_1.Trace.enable;
exports.error = core_1.Trace.error;
exports.getErrorHandler = core_1.Trace.getErrorHandler;
exports.isCategorySet = core_1.Trace.isCategorySet;
exports.isEnabled = core_1.Trace.isEnabled;
exports.notifyEvent = core_1.Trace.notifyEvent;
exports.setCategories = core_1.Trace.setCategories;
exports.setErrorHandler = core_1.Trace.setErrorHandler;
exports.write = core_1.Trace.write;
exports.removeWriter = core_1.Trace.removeWriter;
exports.messageType = core_1.Trace.messageType;
exports.removeEventListener = core_1.Trace.removeEventListener;
exports.addCategories = core_1.Trace.addCategories;
exports.addEventListener = core_1.Trace.addEventListener;
exports.DefaultErrorHandler = core_1.Trace.DefaultErrorHandler;
exports.ConsoleWriter = core_1.Trace.ConsoleWriter;
exports.addWriter = core_1.Trace.addWriter;
exports.categories = core_1.Trace.categories;
exports.clearWriters = core_1.Trace.clearWriters;
exports.disable = core_1.Trace.disable;
