#ifndef CBINDGEN_BINDINGS_H
#define CBINDGEN_BINDINGS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct CCow CCow;

typedef struct F32Buffer F32Buffer;

typedef struct I32Buffer I32Buffer;

typedef struct StringBuffer StringBuffer;

typedef struct TextDecoder TextDecoder;

typedef struct TextEncoder TextEncoder;

typedef struct U16Buffer U16Buffer;

typedef struct U32Buffer U32Buffer;

typedef struct U8Buffer U8Buffer;

typedef struct URL URL;

struct U8Buffer *nativescript_core_atob(const char *value);

struct U8Buffer *nativescript_core_atob_ccow(const struct CCow *value);

struct CCow *nativescript_core_btoa(const char *value);

struct CCow *nativescript_core_btoa_ccow(const struct CCow *value);

void nativescript_core_string_destroy(char *value);

bool nativescript_core_url_can_parse(const char *value, const char *base);

struct URL *nativescript_core_url_create(const char *value, const char *base);

void nativescript_core_url_destroy(struct URL *url);

struct CCow *nativescript_core_url_to_string(struct URL *url);

const char *nativescript_core_url_hash(struct URL *url);

void nativescript_core_url_set_hash(struct URL *url, const char *hash);

const char *nativescript_core_url_host(struct URL *url);

void nativescript_core_url_set_host(struct URL *url, const char *host);

const char *nativescript_core_url_host_name(struct URL *url);

void nativescript_core_url_set_host_name(struct URL *url, const char *hostname);

const char *nativescript_core_url_href(struct URL *url);

void nativescript_core_url_set_href(struct URL *url, const char *href);

const char *nativescript_core_url_origin(struct URL *url);

const char *nativescript_core_url_password(struct URL *url);

void nativescript_core_url_set_password(struct URL *url, const char *password);

const char *nativescript_core_url_pathname(struct URL *url);

void nativescript_core_url_set_pathname(struct URL *url, const char *pathname);

const char *nativescript_core_url_port(struct URL *url);

void nativescript_core_url_set_port(struct URL *url, const char *port);

const char *nativescript_core_url_protocol(struct URL *url);

void nativescript_core_url_set_protocol(struct URL *url, const char *protocol);

const char *nativescript_core_url_search(struct URL *url);

void nativescript_core_url_set_search(struct URL *url, const char *search);

const char *nativescript_core_url_username(struct URL *url);

void nativescript_core_url_set_username(struct URL *url, const char *username);

void nativescript_core_ccow_destroy(struct CCow *cow);

const uint8_t *nativescript_core_ccow_get_bytes(const struct CCow *cow);

uintptr_t nativescript_core_ccow_get_length(const struct CCow *cow);

struct TextDecoder *nativescript_core_text_decoder_create(const char *decoding);

const char *nativescript_core_text_decoder_decode(const struct TextDecoder *decoder,
                                                  const uint8_t *data,
                                                  uintptr_t size);

struct CCow *nativescript_core_text_decoder_decode_as_cow(const struct TextDecoder *decoder,
                                                          const uint8_t *data,
                                                          uintptr_t size);

struct U8Buffer *nativescript_core_text_decoder_decode_as_bytes(const struct TextDecoder *decoder,
                                                                const uint8_t *data,
                                                                uintptr_t size);

void nativescript_core_text_decoder_destroy(struct TextDecoder *value);

const char *nativescript_core_text_decoder_get_encoding(const struct TextDecoder *decoder);

struct TextEncoder *nativescript_core_text_encoder_create(const char *encoding);

struct U8Buffer *nativescript_core_text_encoder_encode(const struct TextEncoder *encoder,
                                                       const char *text);

const char *nativescript_core_text_encoder_get_encoding(const struct TextEncoder *encoder);

void nativescript_core_text_encoder_destroy(struct TextEncoder *value);

const uint8_t *nativescript_core_u8_buffer_get_bytes(const struct U8Buffer *buffer);

uint8_t *nativescript_core_u8_buffer_get_bytes_mut(struct U8Buffer *buffer);

void nativescript_core_u8_buffer_destroy(struct U8Buffer *buffer);

uintptr_t nativescript_core_u8_buffer_get_length(const struct U8Buffer *buffer);

const uint16_t *nativescript_core_u16_buffer_get_bytes(const struct U16Buffer *buffer);

uint16_t *nativescript_core_u16_buffer_get_bytes_mut(struct U16Buffer *buffer);

void nativescript_core_u16_buffer_destroy(struct U16Buffer *buffer);

uintptr_t nativescript_core_u16_buffer_get_length(const struct U16Buffer *buffer);

const uint32_t *nativescript_core_u32_buffer_get_bytes(const struct U32Buffer *buffer);

uint32_t *nativescript_core_u32_buffer_get_bytes_mut(struct U32Buffer *buffer);

void nativescript_core_u32_buffer_destroy(struct U32Buffer *buffer);

uintptr_t nativescript_core_u32_buffer_get_length(const struct U32Buffer *buffer);

const int32_t *nativescript_core_i32_buffer_get_bytes(const struct I32Buffer *buffer);

int32_t *nativescript_core_i32_buffer_get_bytes_mut(struct I32Buffer *buffer);

void nativescript_core_i32_buffer_destroy(struct I32Buffer *buffer);

uintptr_t nativescript_core_i32_buffer_get_length(const struct I32Buffer *buffer);

const float *nativescript_core_f32_buffer_get_bytes(const struct F32Buffer *buffer);

float *nativescript_core_f32_buffer_get_bytes_mut(struct F32Buffer *buffer);

void nativescript_core_f32_buffer_destroy(struct F32Buffer *buffer);

uintptr_t nativescript_core_f32_buffer_get_length(const struct F32Buffer *buffer);

uintptr_t nativescript_core_string_buffer_get_length(const struct StringBuffer *buffer);

char *nativescript_core_string_buffer_get_value_at(const struct StringBuffer *buffer,
                                                   uintptr_t index);

void nativescript_core_string_buffer_destroy(struct StringBuffer *buffer);

#endif /* CBINDGEN_BINDINGS_H */
