export const NS_NATIVE_TAGS = new Set<string>([
	// Core containers/layouts
	'Page',
	'Frame',
	'ActionItem',
	'NavigationButton',
	'GridLayout',
	'StackLayout',
	'FlexboxLayout',
	'DockLayout',
	'AbsoluteLayout',
	'WrapLayout',
	'ContentView',
	// Common views
	'Label',
	'Span',
	'FormattedString',
	'Button',
	'Image',
	'Img',
	'ListView',
	'CollectionView',
	'ScrollView',
	'WebView',
	'Switch',
	'Slider',
	'Progress',
	'ActivityIndicator',
	'SearchBar',
	'TextField',
	'TextView',
	// Tabs/Navigation
	'TabView',
	'TabViewItem',
	'BottomNavigation',
	'Tabs',
	'TabStrip',
	'TabStripItem',
	'TabContentItem',
	// Misc/Plugins (non-exhaustive; safe as custom elements)
	'MapView',
	'LottieView',
	'Video',
	'VideoPlayer',
	'Chart',
	'Calendar',
	// Additional common NS elements
	'ActionItems',
	'NavigationButton',
	'DatePicker',
	'TimePicker',
	'SegmentedBar',
	'SegmentedBarItem',
	'RadListView',
	'CollectionViewGridLayout',
	'StackLayoutBase',
	'FlexboxLayoutBase',
	'GridLayoutBase',
	'RadSideDrawer',
	'SideDrawer',
	'DrawerContent',
	'MainContent',
	'CardView',
	'Ripple',
	'Fab',
	'FloatingActionButton',
	'BottomSheet',
	'Snackbar',
	'ImgCache',
	'ImgPlaceholder',
]);

export function isNativeTag(tag: string): boolean {
	return NS_NATIVE_TAGS.has(tag);
}
