//
//  TNSFsConstants.m
//  TNSWidgets
//
//  Created by Osei Fortune on 23/02/2022.
//  Copyright © 2022 Telerik A D. All rights reserved.
//
#import "TNSFsConstants.h"

@implementation TNSFsConstants

+ (unsigned int)FILE_COPY_OPTIONS_COPYFILE_EXCL {
    return FILE_COPY_OPTIONS_COPYFILE_EXCL;
}

+ (unsigned int)FILE_COPY_OPTIONS_COPYFILE_FICLONE {
    return FILE_COPY_OPTIONS_COPYFILE_FICLONE;
}

+ (unsigned int)FILE_COPY_OPTIONS_COPYFILE_FICLONE_FORCE {
    return FILE_COPY_OPTIONS_COPYFILE_FICLONE_FORCE;
}

+(int) FILE_OPEN_OPTIONS_O_RDONLY {
    return FILE_OPEN_OPTIONS_O_RDONLY;
}

+(int) FILE_OPEN_OPTIONS_O_WRONLY {
    return FILE_OPEN_OPTIONS_O_WRONLY;
}

+(int) FILE_OPEN_OPTIONS_O_RDWR {
    return FILE_OPEN_OPTIONS_O_RDWR;
}

+(int) FILE_OPEN_OPTIONS_O_CREAT {
    return FILE_OPEN_OPTIONS_O_CREAT;
}

+(int) FILE_OPEN_OPTIONS_O_EXCL {
    return FILE_OPEN_OPTIONS_O_EXCL;
}

+(int) FILE_OPEN_OPTIONS_O_NOCTTY {
    return FILE_OPEN_OPTIONS_O_NOCTTY;
}

+(int) FILE_OPEN_OPTIONS_O_TRUNC {
    return FILE_OPEN_OPTIONS_O_TRUNC;
}

+(int) FILE_OPEN_OPTIONS_O_APPEND {
    return FILE_OPEN_OPTIONS_O_APPEND;
}

+(int) FILE_OPEN_OPTIONS_O_DIRECTORY {
    return FILE_OPEN_OPTIONS_O_DIRECTORY;
}

+(int) FILE_OPEN_OPTIONS_O_NOATIME {
    return FILE_OPEN_OPTIONS_O_NOATIME;
}

+(int) FILE_OPEN_OPTIONS_O_NOFOLLOW {
    return FILE_OPEN_OPTIONS_O_NOFOLLOW;
}

+(int) FILE_OPEN_OPTIONS_O_SYNC {
    return FILE_OPEN_OPTIONS_O_SYNC;
}

+(int) FILE_OPEN_OPTIONS_O_DSYNC {
    return FILE_OPEN_OPTIONS_O_DSYNC;
}

+(int) FILE_OPEN_OPTIONS_O_SYMLINK {
    return FILE_OPEN_OPTIONS_O_SYMLINK;
}

+(int) FILE_OPEN_OPTIONS_O_DIRECT {
    return FILE_OPEN_OPTIONS_O_DIRECT;
}

+(int) FILE_OPEN_OPTIONS_O_NONBLOCK {
    return FILE_OPEN_OPTIONS_O_NONBLOCK;
}

+(int) FILE_ACCESS_OPTIONS_F_OK {
    return FILE_ACCESS_OPTIONS_F_OK;
}

+(int) FILE_ACCESS_OPTIONS_R_OK {
    return FILE_ACCESS_OPTIONS_R_OK;
}

+(int) FILE_ACCESS_OPTIONS_W_OK {
    return FILE_ACCESS_OPTIONS_W_OK;
}

+(int) FILE_ACCESS_OPTIONS_X_OK {
    return FILE_ACCESS_OPTIONS_X_OK;
}

+(mode_t) FILE_TYPE_OPTIONS_S_IFMT {
    return FILE_TYPE_OPTIONS_S_IFMT;
}

+(mode_t) FILE_TYPE_OPTIONS_S_IFREG {
    return FILE_TYPE_OPTIONS_S_IFREG;
}

+(mode_t) FILE_TYPE_OPTIONS_S_IFDIR {
    return FILE_TYPE_OPTIONS_S_IFDIR;
}

+(mode_t) FILE_TYPE_OPTIONS_S_IFCHR {
    return FILE_TYPE_OPTIONS_S_IFCHR;
}

+(mode_t) FILE_TYPE_OPTIONS_S_IFBLK {
    return FILE_TYPE_OPTIONS_S_IFBLK;
}

+(mode_t) FILE_TYPE_OPTIONS_S_IFIFO{
    return FILE_TYPE_OPTIONS_S_IFIFO;
}

+(mode_t) FILE_TYPE_OPTIONS_S_IFLNK {
    return FILE_TYPE_OPTIONS_S_IFLNK;
}

+(mode_t) FILE_TYPE_OPTIONS_S_IFSOCK{
    return FILE_TYPE_OPTIONS_S_IFSOCK;
}

+(mode_t) FILE_MODE_OPTIONS_S_IRWXU {
    return FILE_MODE_OPTIONS_S_IRWXU;
}

+(mode_t) FILE_MODE_OPTIONS_S_IRUSR {
    return FILE_MODE_OPTIONS_S_IRUSR;
}

+(mode_t) FILE_MODE_OPTIONS_S_IWUSR {
    return FILE_MODE_OPTIONS_S_IWUSR;
}

+(mode_t) FILE_MODE_OPTIONS_S_IXUSR {
    return FILE_MODE_OPTIONS_S_IXUSR;
}

+(mode_t) FILE_MODE_OPTIONS_S_IRWXG {
    return FILE_MODE_OPTIONS_S_IRWXG;
}

+(mode_t) FILE_MODE_OPTIONS_S_IRGRP {
    return FILE_MODE_OPTIONS_S_IRGRP;
}

+(mode_t) FILE_MODE_OPTIONS_S_IWGRP {
    return FILE_MODE_OPTIONS_S_IWGRP;
}

+(mode_t) FILE_MODE_OPTIONS_S_IXGRP {
    return FILE_MODE_OPTIONS_S_IXGRP;
}

+(mode_t) FILE_MODE_OPTIONS_S_IRWXO {
    return FILE_MODE_OPTIONS_S_IRWXO;
}

+(mode_t) FILE_MODE_OPTIONS_S_IROTH {
    return FILE_MODE_OPTIONS_S_IROTH;
}

+(mode_t) FILE_MODE_OPTIONS_S_IWOTH {
    return FILE_MODE_OPTIONS_S_IWOTH;
}

+(mode_t) FILE_MODE_OPTIONS_S_IXOTH {
    return FILE_MODE_OPTIONS_S_IXOTH;
}

@end
