/**
 * Contains the all UI classes.
 */
declare module "ui" {
    export * from "ui/action-bar";
    export * from "ui/activity-indicator";
    export * from "ui/builder";
    export * from "ui/button";
    export * from "ui/content-view";
    export * from "ui/core/bindable";
    export * from "ui/core/dependency-observable";
    export * from "ui/core/proxy";
    export * from "ui/core/view";
    export * from "ui/core/weak-event-listener";
    export * from "ui/dialogs";
    export * from "ui/date-picker";
    export * from "ui/editable-text-base";
    export * from "ui/enums";
    export * from "ui/frame";
    export * from "ui/gestures";
    export * from "ui/html-view";
    export * from "ui/image";
    export * from "ui/image-cache";
    export * from "ui/label";
    export * from "ui/layouts/layout-base";
    export * from "ui/layouts/layout";
    export * from "ui/layouts/absolute-layout";
    export * from "ui/layouts/dock-layout";
    export * from "ui/layouts/grid-layout";
    export * from "ui/layouts/stack-layout";
    export * from "ui/layouts/wrap-layout";
    export * from "ui/list-picker";
    export * from "ui/list-view";
    export * from "ui/page";
    export * from "ui/placeholder";
    export * from "ui/progress";
    export * from "ui/repeater";
    export * from "ui/scroll-view";
    export * from "ui/search-bar";
    export * from "ui/segmented-bar";
    export * from "ui/slider";
    export * from "ui/styling";
    export * from "ui/styling/background";
    export * from "ui/styling/css-selector";
    export * from "ui/styling/font";
    export * from "ui/styling/style-property";
    export * from "ui/styling/visual-state-constants";
    export * from "ui/switch";
    export * from "ui/tab-view";
    export * from "ui/text-base";
    export * from "ui/text-field";
    export * from "ui/text-view";
    export * from "ui/time-picker";
    export * from "ui/web-view";
}