// Auto-generated by typings-generator (dotnet mode).
// Do not edit - re-run build.windows.ps1 to regenerate.

declare namespace NativeScript.Widgets {
    class FlexboxLayout extends Microsoft.UI.Xaml.Controls.Panel implements NativeScript.Widgets.IFlexboxLayout {
      JustifyContent: number;
      FlexWrap: number;
      FlexDirection: number;
      AlignItems: number;
      AlignContent: number;
      constructor();
      static GetOrder(result: Microsoft.UI.Xaml.UIElement): number;
      static SetOrder(element: Microsoft.UI.Xaml.UIElement, value: number): void;
      static GetFlexGrow(result: Microsoft.UI.Xaml.UIElement): number;
      static SetFlexGrow(element: Microsoft.UI.Xaml.UIElement, value: number): void;
      static GetFlexShrink(result: Microsoft.UI.Xaml.UIElement): number;
      static SetFlexShrink(element: Microsoft.UI.Xaml.UIElement, value: number): void;
      static GetAlignSelf(result: Microsoft.UI.Xaml.UIElement): number;
      static SetAlignSelf(element: Microsoft.UI.Xaml.UIElement, value: number): void;
      static GetFlexBasisPercent(result: Microsoft.UI.Xaml.UIElement): number;
      static SetFlexBasisPercent(element: Microsoft.UI.Xaml.UIElement, value: number): void;
      static GetWrapBefore(result: Microsoft.UI.Xaml.UIElement): boolean;
      static SetWrapBefore(element: Microsoft.UI.Xaml.UIElement, value: boolean): void;
    }
    class ImageHelper {
      static LoadFromBufferAsync(operation: Windows.Storage.Streams.IBuffer): Windows.Foundation.IAsyncOperation<NativeScript.Widgets.ImageResult>;
      static LoadFromUrlAsync(operation: string): Windows.Foundation.IAsyncOperation<NativeScript.Widgets.ImageResult>;
      static LoadFromFileAsync(operation: string): Windows.Foundation.IAsyncOperation<NativeScript.Widgets.ImageResult>;
      static ResizeAsync(operation: Windows.Storage.Streams.IBuffer, buffer: number): Windows.Foundation.IAsyncOperation<NativeScript.Widgets.ImageResult>;
      static SaveToFileAsync(operation: Windows.Storage.Streams.IBuffer, buffer: string): Windows.Foundation.IAsyncOperation<boolean>;
      static ReadFileAsync(operation: string): Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IBuffer>;
      static BufferToBase64(result: Windows.Storage.Streams.IBuffer): string;
    }
    class ImageResult implements NativeScript.Widgets.IImageResult {
      readonly Bitmap: Microsoft.UI.Xaml.Media.Imaging.BitmapImage;
      readonly Height: number;
      readonly RawBuffer: Windows.Storage.Streams.IBuffer;
      readonly Width: number;
    }
    class ShadowHelper {
      static CreateShadow(result: number, width: number, height: number, blurRadius: number, spread: number, cornerRadius: number, offsetX: number, offsetY: number): NativeScript.Widgets.ShadowImageResult;
      static CreateBorder(result: number, width: number, height: number, topW: number, rightW: number, bottomW: number, leftW: number, topArgb: number, rightArgb: number, bottomArgb: number, leftArgb: number): NativeScript.Widgets.ShadowImageResult;
    }
    class ShadowImageResult implements NativeScript.Widgets.IShadowImageResult {
      readonly Height: number;
      readonly Image: Microsoft.UI.Xaml.Controls.Image;
      readonly Overhang: number;
      readonly Width: number;
    }
    class StackLayout extends Microsoft.UI.Xaml.Controls.Panel implements NativeScript.Widgets.IStackLayout {
      Orientation: number;
      constructor();
    }
}

