// Auto-generated by typings-generator (dotnet mode).

  namespace NativeScript.Widgets {
    class ImageResult {
      readonly Bitmap: Windows.UI.Xaml.Media.Imaging.BitmapImage;
      readonly RawBuffer: Windows.Storage.Streams.IBuffer;
      readonly Width: number;
      readonly Height: number;
    }

    class ImageHelper {
      static LoadFromBufferAsync(buffer: Windows.Storage.Streams.IBuffer): Windows.Foundation.IAsyncOperation<ImageResult>;
      static LoadFromUrlAsync(url: string): Windows.Foundation.IAsyncOperation<ImageResult>;
      static LoadFromFileAsync(path: string): Windows.Foundation.IAsyncOperation<ImageResult>;
      static ResizeAsync(buffer: Windows.Storage.Streams.IBuffer, maxSize: number): Windows.Foundation.IAsyncOperation<ImageResult>;
      static SaveToFileAsync(buffer: Windows.Storage.Streams.IBuffer, path: string): Windows.Foundation.IAsyncOperation<boolean>;
      static ReadFileAsync(path: string): Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IBuffer>;
      static BufferToBase64(buffer: Windows.Storage.Streams.IBuffer): string;
    }

    class CompositionBorderHelper {
      static Create(element: Windows.UI.Xaml.UIElement): CompositionBorderHelper | null;
      UpdateBorderWidth(left: number, top: number, right: number, bottom: number): void;
      UpdateBorderColor(left: number, top: number, right: number, bottom: number): void;
      UpdateBorderRadius(tl: number, tr: number, br: number, bl: number): void;
      Free(): void;
    }

    class FlexboxLayout extends Windows.UI.Xaml.Controls.Panel {
      static readonly FlexDirectionProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly FlexWrapProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly JustifyContentProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly AlignItemsProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly AlignContentProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly OrderProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly FlexGrowProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly FlexShrinkProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly AlignSelfProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly FlexBasisPercentProperty: Windows.UI.Xaml.DependencyProperty;
      static readonly WrapBeforeProperty: Windows.UI.Xaml.DependencyProperty;
      FlexDirection: number;
      FlexWrap: number;
      JustifyContent: number;
      AlignItems: number;
      AlignContent: number;
      static GetOrder(e: Windows.UI.Xaml.UIElement): number;
      static SetOrder(e: Windows.UI.Xaml.UIElement, v: number): void;
      static GetFlexGrow(e: Windows.UI.Xaml.UIElement): number;
      static SetFlexGrow(e: Windows.UI.Xaml.UIElement, v: number): void;
      static GetFlexShrink(e: Windows.UI.Xaml.UIElement): number;
      static SetFlexShrink(e: Windows.UI.Xaml.UIElement, v: number): void;
      static GetAlignSelf(e: Windows.UI.Xaml.UIElement): number;
      static SetAlignSelf(e: Windows.UI.Xaml.UIElement, v: number): void;
      static GetFlexBasisPercent(e: Windows.UI.Xaml.UIElement): number;
      static SetFlexBasisPercent(e: Windows.UI.Xaml.UIElement, v: number): void;
      static GetWrapBefore(e: Windows.UI.Xaml.UIElement): boolean;
      static SetWrapBefore(e: Windows.UI.Xaml.UIElement, v: boolean): void;
    }
  }
